### ISSUE TITLE
Downsides of high position tolerance?

### ISSUE THREAD

**Issue by callym** [redox-os/rusttype#107]
I was playing with the gpu cache, and wondered why I was getting repeated glyphs when caching a string like "Hello World!", then found that putting the position tolerance up to 2.0 means that only one copy of each glyph is cached, which is what I was expecting to begin with. 

What are the downsides of having a high position tolerance, considering the default is 0.1?

**Comment by alexheretic** [comment]
Position means **sub-pixel position**, any value greater than or equal to 1.0 means _"don't care"_. This can cause kerning to be misaligned due to sub-x errors, but more obviously in multi-line layouts sub-y offset issues can look quite bad as all glyphs of the same scale will have the same sub-y position.

For example taking a section of the gfx-glyph paragraph example shows this fairly clearly
## With default (0.1) position tolerance
![](https://user-images.githubusercontent.com/2331607/38473193-b101bfc6-3b83-11e8-9aef-8c015967671a.png)

## Don't care position tolerance (1.0)
![](https://user-images.githubusercontent.com/2331607/38473199-c1565850-3b83-11e8-9c77-aa0fa7d714d7.png)

However, in some situations you may be sure that sub-pixel positions are not an issue. Maybe using very large glyph scales. Position tolerance `1.0` will perform better and require a smaller texture, but in general `0.1` or even lower is a good fit.

**Comment by alexheretic** [comment]
I think this answers the question so I'll close
