### ISSUE TITLE
Glyph artifacts when using glyph cache

### ISSUE THREAD

**Issue by Boscop** [redox-os/rusttype#28]
When I render glyphs like in the gpu_cache example, I get artifacts like this:
![b08hgrg](https://cloud.githubusercontent.com/assets/535593/19415156/a0cfc19a-9367-11e6-8e7e-53c269a32c78.png)

It looks like it's caused by glyphs being tightly packed in the texture and OpenGL trying to interpolate because of `self.cache_tex.sampled().magnify_filter(glium::uniforms::MagnifySamplerFilter::Nearest)`.
But the problem persists when I change that to Linear.
Maybe it could be solved by leaving 1 pixel space between glyphs horizontally and vertically?
Or maybe there is a better solution by choosing a different way for OpenGL to access the texture data?

**Comment by dylanede** [comment]
From the screenshot it looks like you might be upscaling the text or rendering the textures at fractional pixel offsets? It seems that the text itself is overly blurry which would be caused by doing either of those things. The GPU cache is designed for rendering at a one-to-one scale. If this is done, with 'nearest' filtering and no fractional pixel offsets for the rendered texture on the screen it should be impossible to get this texture bleeding (bar driver bugs - but drivers are pretty good these days). Doing this allows the cache texture to be packed as tightly as it is.

If the above guarantees are relaxed then you are giving up the accuracy of the text rendering and the interpolation will decrease legibility. Also, adding a pixel border would not be enough in many circumstances - you would need to pick some arbitrary border width that removes the bleeding for the scales you're rendering at. If you want to render text more dynamically then GPU vector rendering would be more appropriate.

**Comment by Jonesey13** [comment]
I also encountered this problem when scaling beyond powers of 2 and transforming the text (rotation). One thing that helps mitigate the problem is setting the default value the texture is initialized to to zero:

``` rust
let cache_tex = glium::texture::Texture2d::with_format(
     &*display,
     glium::texture::RawImage2d {
     data: Cow::Owned(vec![128u8; cache_width as usize * cache_height as usize]),
     width: cache_width,
     height: cache_height,
     format: glium::texture::ClientFormat::U8
 },
```
Changing 128u8 to 0u8 reduced the problem but not completely (since other neighbouring glyphs can interfere). 

>Maybe it could be solved by leaving 1 pixel space between glyphs horizontally and vertically?

I've tried to implement this myself and I seem to have something that works (I think 1pixel padding should be enough for rendering up-scaled font textures, right @dylanede?). I've raised a PR for this if you still want to give this a try but it may be error prone.
