### ISSUE TITLE
A option to disable font anti-aliasing?

### ISSUE THREAD

**Issue by expenses** [redox-os/rusttype#61]
Anti-aliased fonts are fantastic, 99% of the time. But for some applications, generally games, unaliased fonts can preferred for aesthetic reasons. Do you think it would be possible to have an option to turn the font antialiasing off?

**Comment by lo48576** [comment]
TTF font has (usually) vector font.
For every pixel, rusttype calculates "coverage", which is percentage of area covered by glyphs (described by vector format).
So rusttype does not "anti-alias" for raster bitmap, but does "**rasterize**" for vector glyph images.

I think you had better use bitmap font directly, because it doesn't need to be rasterized.

You can use rusttype to get binarized fonts **by [`round`](https://doc.rust-lang.org/std/primitive.f32.html#method.round)ing the coverage value** given by [`PositionedGlyph::draw`](https://docs.rs/rusttype/0.2.3/rusttype/struct.PositionedGlyph.html#method.draw), but it may cause readability issue.
(Pixel coverages of arrow lines may be very low and can be rounded to zero!)
I don't know how to do this easy with [glyph cache](https://docs.rs/rusttype/0.2.3/rusttype/gpu_cache/struct.Cache.html)...

**Comment by dylanede** [comment]
@expenses this is doable without modifying RustType. As @lo48576 describes, you can round the coverage value given by `draw`. For use with the glyph cache feature, you can simply do a similar rounding conversion within the closure passed to `cache_queued`. Be aware though that many fonts are not designed with binary aliasing in mind, and may end up looking pretty bad.

**Comment by expenses** [comment]
@ids1024 @dylanede Thank you for the advice! However, `round`ing the coverage value doesn't quite get the result I was looking for. Here is the font with anti-aliasing on, off and what I'd ideally like:
![rendering](https://user-images.githubusercontent.com/13566135/31053075-9fa33c9a-a6f1-11e7-9735-bcb3ba766ddd.png)

Is this something that could be fixed with kerning?

**Comment by dylanede** [comment]
@expenses Do you mind posting a comparison with the glyph positions rounded?

**Comment by expenses** [comment]
@dylanede Sure! 
![](https://user-images.githubusercontent.com/13566135/31061580-6575c0ea-a77f-11e7-862f-0978ccdbe77f.png)

Font is [TinyUnicode](https://www.dafont.com/tinyunicode.font) by the way.

**Comment by alexheretic** [comment]
Since `draw` gives you the alpha, and using the gpu_cache you can define rounding in a shader, I guess rusttype users should have what they need to handle this issue. Can we close?
